global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'config-server'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.137.109:8888' ]
  - job_name: 'discovery-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.137.109:8761' ]
  - job_name: 'gateway'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.137.109:8080' ]
  - job_name: 'customer-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.137.109:8090' ]
  - job_name: 'card-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.137.109:8100' ]
  - job_name: 'account-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.137.109:8110' ]
