apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: dt-bank
spec:
  selector:
    app: keycloak
  type: ClusterIP # Expose internally first. Use an Ingress for external access.
  ports:
    - name: http
      port: 8080
      targetPort: keycloak-http
    - name: https
      port: 8443
      targetPort: keycloak-https
    - name: mgmt
      port: 9000
      targetPort: keycloak-mgmt