apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: dt-bank
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "ghcr.io/ajharry69/keycloak:26.2"
          args: ["start", "--optimized", "--proxy-headers", "xforwarded"]
          ports:
            - name: keycloak-http
              containerPort: 8080
            - name: keycloak-https
              containerPort: 8443
            - name: keycloak-mgmt
              containerPort: 9000
          env:
            # This helps Keycloak generate correct issuer URLs.
            # For production, this should be your public-facing domain.
            - name: KC_HOSTNAME
              value: "https://oauth.xently.co.ke"
            # This allows Keycloak to be accessed via HTTP, which is common
            # inside a cluster where a separate Ingress handles TLS termination.
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-database.dt-bank.svc.cluster.local:5432/authentication"
            - name: KC_DB_USERNAME
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: DB_USERNAME } }
            - name: KC_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: DB_PASSWORD } }
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: ADMIN_USERNAME } }
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: ADMIN_PASSWORD } }
          volumeMounts:
            - name: keycloak-storage
              mountPath: /opt/keycloak/data
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 90
            periodSeconds: 20
      volumes:
        - name: keycloak-storage
          persistentVolumeClaim:
            claimName: keycloak-pvc