apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dt-bank
stringData: # For readability. In a real CD pipeline, use a secrets manager like Vault or GCP Secret Manager.
  POSTGRES_USER: "test"
  POSTGRES_PASSWORD: "test"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: dt-bank
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: dt-bank
stringData:
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"