apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: dt-bank
spec:
  selector:
    app: config-server
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: config-server-http