services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./gateway/src/test/resources/realm.json:/opt/keycloak/data/import/realm.json:ro
    command: start-dev --import-realm

  rabbitmq:
    image: "rabbitmq:4.1-alpine"
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    ports:
      - "5672:5672"
    volumes:
      - mq_data:/var/lib/rabbitmq

  zipkin:
    image: "openzipkin/zipkin:3.5"
    ports:
      - "9411:9411"

volumes:
  mq_data: