apiVersion: v1
kind: Service
metadata:
  name: account-service-database
  namespace: dt-bank
spec:
  selector:
    app: account-service-database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: account-svc-db