apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: dt-bank
spec:
  template:
    spec:
      containers:
        - name: keycloak
          args: ["start-dev", "--import-realm"]
          env:
            - name: KC_HOSTNAME
              value: "https://keycloak.dt-bank.svc.cluster.local:8443"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/opt/keycloak/conf/server.crt.pem"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/opt/keycloak/conf/server.key.pem"