name: "Setup Gradle Environment"
description: "Checks out code, and sets up Java and Gradle."

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "24"
        cache: "gradle"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4