apiVersion: v1
kind: Service
metadata:
  name: customer-service-database
  namespace: dt-bank
spec:
  selector:
    app: customer-service-database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: customer-svc-db