apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: dt-bank
spec:
  selector:
    app: customer-service
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: customer-svc-http