apiVersion: v1
kind: Service
metadata:
  name: card-service-database
  namespace: dt-bank
spec:
  selector:
    app: card-service-database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: card-svc-db