apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: dt-bank
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: discovery
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service-discovery
  namespace: dt-bank
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service
  # Allow not-yet-ready Pods to be visible to ensure the forming of a cluster if Pods come up concurrently
  publishNotReadyAddresses: true
  clusterIP: None
  type: ClusterIP