apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-service
  namespace: dt-bank
  labels:
    app: discovery-service
spec:
  serviceName: discovery-service-discovery
  # Run with one replica to save resources, or with two replicas to allow for rolling updates for configuration changes
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: discovery-service
          image: ghcr.io/ajharry69/discovery-service:1.0.3 # This image tag will be updated by your CD pipeline
          ports:
            - name: discovery
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: CONFIG_SERVER_URL
              value: "http://config-server.dt-bank.svc.cluster.local:8080"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
