server:
  port: 8110
spring:
  threads:
    virtual:
      enabled: true
springdoc:
  paths-to-match: /api/**
  api-docs:
    path: /account-service/v3/api-docs
  swagger-ui:
    path: /account-service/swagger-ui.html