application:
  config:
    gateway:
      url: "http://localhost:8080"
management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  metrics:
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
server:
  forward-headers-strategy: framework
spring:
  cloud:
    config:
      fail-fast: true
      retry:
        # Start with a 1.5-second delay
        initial-interval: 1500
        # Increase the delay by 20% after each failed attempt
        multiplier: 1.2
        # Cap the delay at 5 seconds between retries
        max-interval: 5000
        # Try up to 20 times before giving up. (20 retries * ~3s avg = ~1 min)
        max-attempts: 20
  docker:
    compose:
      file:
        - compose.ide.yaml
      skip:
        in-tests: false
      stop:
        command: down
  datasource:
    username: "${spring.flyway.user}"
    password: "${spring.flyway.password}"
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: test-client
            client-secret: test-secret
            scope:
              - offline_access
              - openid
              - customer.read
              - card.update
              - card.delete
              - account.update
              - account.delete
              - customer.create
              - card.read
              - account.read
              - customer.update
              - card.create
              - customer.delete
              - account.create
        provider:
          keycloak:
            issuer-uri: "${spring.security.oauth2.resourceserver.jwt.issuer-uri}"
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/dt-bank"
  threads:
    virtual:
      enabled: true
springdoc:
  paths-to-match: /api/**