application:
  config:
    gateway:
      url: "http://host.docker.internal:8080"
eureka:
  client:
    service-url:
      defaultZone: "http://discovery-service:8080/eureka/"
management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
spring:
  data:
    redis:
      host: "redis"
  rabbitmq:
    host: "rabbitmq"
  flyway:
    user: "test"
    password: "test"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://host.docker.internal:8443/realms/dt-bank"
