application:
  config:
    gateway:
      url: http://localhost:8080
management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  metrics:
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
server:
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: test-client
            client-secret: test-secret
            scope:
              - offline_access
              - openid
              - customer.read
              - card.update
              - card.delete
              - account.update
              - account.delete
              - customer.create
              - card.read
              - account.read
              - customer.update
              - card.create
              - customer.delete
              - account.create
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_BASE_URL:http://localhost:8180}/realms/dt-bank
  threads:
    virtual:
      enabled: true
springdoc:
  paths-to-match: /api/**