application:
  config:
    card-url: http://localhost:8080/api/v1/cards
    account-url: http://localhost:8080/api/v1/accounts
    customer-url: http://localhost:8080/api/v1/customers
management:
  tracing:
    sampling:
      probability: 1
server:
  forward-headers-strategy: framework
spring:
  threads:
    virtual:
      enabled: true
springdoc:
  paths-to-match: /api/**