application:
  config:
    gateway:
      url: http://localhost:8080
management:
  tracing:
    sampling:
      probability: 1
server:
  forward-headers-strategy: framework
spring:
  threads:
    virtual:
      enabled: true
springdoc:
  paths-to-match: /api/**