server:
  port: 8090
  forward-headers-strategy: framework
management:
  tracing:
    sampling:
      probability: 1
spring:
  threads:
    virtual:
      enabled: true
springdoc:
  paths-to-match: /api/**
  api-docs:
    path: /customer-service/v3/api-docs
  swagger-ui:
    path: /customer-service/swagger-ui.html
application:
  config:
    customer-url: http://localhost:8080/api/v1/customers
    account-url: http://localhost:8080/api/v1/accounts
    card-url: http://localhost:8080/api/v1/cards