apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: dt-bank
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: account-service
          image: ghcr.io/ajharry69/account-service:current
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8080"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: dt-bank
spec:
  selector:
    app: account-service
  type: ClusterIP # Only accessible within the cluster
  ports:
    - port: 8080
      targetPort: 8080

# --- NOTE: Repeat the Deployment and Service blocks above for ---
# --- config-server, discovery-service, card-service, and    ---
# --- customer-service, changing names accordingly.          ---