apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: dt-bank
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: gateway
          image: ghcr.io/ajharry69/gateway:current # This image tag will be updated by your CD pipeline
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes" # Use a k8s-specific profile for service discovery
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8080" # K8s internal DNS
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: dt-bank
spec:
  selector:
    app: gateway
  type: LoadBalancer # Exposes the service externally via a cloud load balancer
  ports:
    - protocol: TCP
      port: 80 # The port on the load balancer
      targetPort: 8080 # The port on the pods