apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: dt-bank
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: dt-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:4.1-alpine"
          ports:
            - name: rabbitmq-amqp
              containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom: { secretKeyRef: { name: rabbitmq-credentials, key: RABBITMQ_DEFAULT_USER } }
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom: { secretKeyRef: { name: rabbitmq-credentials, key: RABBITMQ_DEFAULT_PASS } }
          volumeMounts:
            - name: mq-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: mq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: dt-bank
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: rabbitmq-amqp