name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_ACTOR: ${{github.actor}}
  GITHUB_TOKEN: ${{secrets.GHCR_TOKEN}}

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Upload Test and Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage-reports
          path: |
            build/reports/jacoco/
          retention-days: 5

  build-and-push-current:
    name: Build and Push Docker Images (${{ matrix.version }})
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version:
          - current
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.version }} Docker images
        env:
          IMAGE_VERSION: ${{ matrix.version }}
        run: make build-and-push-images

  release:
    name: Create Release and Push Docker Images
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: build-and-test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "24"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        run: make build-and-push-images
